# Generated by ControlKeel Deployment Advisor
# ---- Build Stage ----
FROM hexpm/elixir:27-erlang-27-alpine-3.20.1 AS build
RUN apk add --no-cache build-base git python3
WORKDIR /app
RUN mix local.hex --force && mix local.rebar --force
ENV MIX_ENV=prod
COPY mix.exs mix.lock ./
RUN mix deps.get --only prod
RUN mkdir config
COPY config/config.exs config/prod.exs config/
RUN mix deps.compile
COPY lib lib
COPY priv priv
RUN mix compile
COPY config/runtime.exs config/
RUN mix release

# ---- Runtime Stage ----
FROM alpine:3.20.1 AS app
RUN apk add --no-cache libstdc++ openssl ncurses-libs
WORKDIR /app
RUN chown nobody /app
ENV MIX_ENV=prod
COPY --from=build --chown=nobody:root /app/_build/prod/idea_release.tar.gz .
RUN tar xzf idea_release.tar.gz -C .
RUN rm idea_release.tar.gz
USER nobody
ENV PHX_SERVER=true
CMD ["/app/bin/idea", "start"]