#!/usr/bin/env sh
set -eu

FILE=".github/workflows/ci.yml"

if [ ! -f "$FILE" ]; then
  echo "missing workflow: $FILE" >&2
  exit 1
fi

must_have() {
  pattern="$1"
  if ! grep -F -- "$pattern" "$FILE" >/dev/null 2>&1; then
    echo "missing required CI pattern: $pattern" >&2
    exit 1
  fi
}

must_not_have() {
  pattern="$1"
  if grep -F -- "$pattern" "$FILE" >/dev/null 2>&1; then
    echo "forbidden CI pattern present: $pattern" >&2
    exit 1
  fi
}

must_have "paths-ignore:"
must_have "concurrency:"
must_have "FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: \"true\""
must_have "- uses: actions/checkout@v6"
must_have "- uses: erlef/setup-beam@v1.23.0"
must_have "- uses: actions/setup-node@v6"
must_have "uses: actions/cache@v5"
must_have "- run: node --check packages/npm/controlkeel/lib/postinstall.js"

must_not_have "# Generated by ControlKeel Deployment Advisor"
must_not_have "- uses: actions/checkout@v4"

if grep -E '^\s*-\s+uses:\s+erlef/setup-beam@v1\s*$' "$FILE" >/dev/null 2>&1; then
  echo "forbidden CI pattern present: erlef/setup-beam@v1 (unpinned)" >&2
  exit 1
fi

echo "CI workflow guard passed"
